/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ushiosan.custom.jfx;

import custom_jfx_plugin.configuration.JfxOptions;
import org.gradle.api.Project;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Test;
import ushiosan.jvm_utilities.system.Platform;

/**
 * A simple unit test for the 'ushiosan.custom.jfx.greeting' plugin.
 */
class CustomJfxPluginPluginTest {
	
	@Test
	void pluginRegistersATask() {
		// Create a test project and apply the plugin
		Project project = ProjectBuilder.builder().build();
		project.getPlugins().apply("ushiosan.custom.jfx.plugin");
		
		project.getExtensions().configure(JfxOptions.class, opts -> {
			opts.platform.set(Platform.LINUX);
		});
		
		// Verify the result
		// assertNotNull(project.getTasks().findByName("greeting"));
	}
	
}
